### ISSUE TITLE
Overwrite save command

### ISSUE THREAD

**Issue by jcubic** [mishoo/ymacs#14]
What is the best way to overwrite save and don't use localStorage for saving files but save them on the server using ajax?

**Comment by mishoo** [comment]
Probably best is to override the `fs_*` functions in `Ymacs.prototype`. (I believe this is what @feeley did in his iOS port?)

See the functions here: https://github.com/mishoo/ymacs/blob/master/src/js/ymacs.js#L524 — by default they just defer to `ls_*` functions, which rely on `localStorage`.

**Comment by feeley** [comment]
Indeed all the fs_* functions in Ymacs.prototype are redefined in the iOS port. It should be fairly easy to make ajax versions because these function take a continuation parameter that needs to be invoked when the operation is done.
