### ISSUE TITLE
YMacs won't build on Ubuntu Studio 

### ISSUE THREAD

**Issue by scarlet31** [mishoo/ymacs#21]
This is after an 'sudo apt install npm' following the ymacs build instructions:

burton@Reactor:~/ymacs$ npm install                                                                 
npm WARN EBADENGINE Unsupported engine {                                                            
npm WARN EBADENGINE   package: 'cosmiconfig@8.3.6',                                                 
npm WARN EBADENGINE   required: { node: '>=14' },                                                   
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }                                   
npm WARN EBADENGINE }                                                                               
npm WARN EBADENGINE Unsupported engine {                                                            
npm WARN EBADENGINE   package: 'node-addon-api@7.1.0',                                              
npm WARN EBADENGINE   required: { node: '^16 || ^18 || >= 20' },                                    
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }                                   
npm WARN EBADENGINE }                                                                               
npm WARN EBADENGINE Unsupported engine {                                                            
npm WARN EBADENGINE   package: 'sass@1.71.1',                                                       
npm WARN EBADENGINE   required: { node: '>=14.0.0' },                                               
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }                                   
npm WARN EBADENGINE }                                                                               
                                                                                                    
up to date, audited 198 packages in 1s                                                              
                                                                                                    
83 packages are looking for funding                                                                 
  run `npm fund` for details                                                                        
                                                                                                    
found 0 vulnerabilities                                                                             
burton@Reactor:~/ymacs$ npx parcel build                                                            
/home/burton/ymacs/node_modules/@parcel/watcher/index.js:32                                         
  if (err?.code !== 'MODULE_NOT_FOUND') {                                                           
          ^                                                                                         
                                                                                                    
SyntaxError: Unexpected token '.'                                                                   
    at wrapSafe (internal/modules/cjs/loader.js:915:16)                                             
    at Module._compile (internal/modules/cjs/loader.js:963:27)                                      
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)                       
    at Module.load (internal/modules/cjs/loader.js:863:32)                                          
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)                                
    at Module.require (internal/modules/cjs/loader.js:887:19)                                       
    at require (internal/modules/cjs/helpers.js:74:18)                                              
    at Object.<anonymous> (/home/burton/ymacs/node_modules/@parcel/fs/lib/index.js:7:28)            
    at Module._compile (internal/modules/cjs/loader.js:999:30)                                      
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

**Comment by mishoo** [comment]
That seems like a very old version of Node, I'm afraid there's nothing we can do here. Just install a newer one using nvm: https://nodejs.org/en/download/package-manager
